openapi: 3.0.0
info:
  description: stackdome-api-server
  title: stackdome-api-server
  version: 0.0.1
servers:
- url: /
paths:
  /api/v1/users:
    post:
      description: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User created successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid request data
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: User already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Create new user
  /api/v1/users/{id}:
    get:
      description: Get a user
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User fetched successfully
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      security:
      - Bearer: []
      summary: Get a user
  /api/v1/users/me:
    get:
      description: Get a the current authenticated user
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User fetched successfully
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      security:
      - Bearer: []
      summary: Get a the current authenticated user
  /api/v1/auth/login:
    post:
      description: Authenticate user and generate an access token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          description: Successful login
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid credentials
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: User login
  /api/v1/workspace-provision-requests:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceProvisionRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceProvisionRequest'
          description: WorkspaceProvisionRequest added successfully
        "400":
          description: Invalid request payload
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Create a new workpace provision request object
  /api/v1/workspace-provision-requests/current:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceProvisionRequest'
          description: WorkspaceProvisionRequest details
        "401":
          description: Unauthorized
        "404":
          description: WorkspaceProvisionRequest object not found
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Get the current users workspace provision request object.
  /api/v1/workspace-provision-requests/{id}:
    delete:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: WorkspaceProvisionRequest deleted successfully
        "401":
          description: Unauthorized
        "404":
          description: WorkspaceProvisionRequest not found
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Delete a WorkspaceProvisionRequest
    get:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceProvisionRequest'
          description: WorkspaceProvisionRequest details
        "401":
          description: Unauthorized
        "404":
          description: WorkspaceProvisionRequest object not found
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Get a workspace provision request object by ID
    put:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceProvisionRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceProvisionRequest'
          description: WorkspaceProvisionRequest updated successfully
        "400":
          description: Invalid request payload
        "401":
          description: Unauthorized
        "404":
          description: WorkspaceProvisionRequest not found
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Update a WorkspaceProvisionRequest
  /api/v1/organizations/{id}/workspace-storages:
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          type: integer
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - explode: true
        in: query
        name: workspaceName
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: state
        required: false
        schema:
          enum:
          - Pending
          - Creating
          - Created
          - Failed
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_v1_organizations__id__workspace_storages_get_200_response'
          description: Successful operation
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: List all WorkspaceStorage objects for an organization
    post:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceStorage'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceStorage'
          description: WorkspaceStorage created successfully
        "400":
          description: Invalid request payload
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Create a new WorkspaceStorage object
  /api/v1/organizations/{org_id}/workspace-storages/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: org_id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: WorkspaceStorage deleted successfully
        "404":
          description: WorkspaceStorage not found
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Delete a WorkspaceStorage object
    get:
      parameters:
      - explode: false
        in: path
        name: org_id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceStorage'
          description: Successful operation
        "404":
          description: WorkspaceStorage not found
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Get a specific WorkspaceStorage object
    put:
      parameters:
      - explode: false
        in: path
        name: org_id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceStorage'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceStorage'
          description: WorkspaceStorage updated successfully
        "400":
          description: Invalid request payload
        "404":
          description: WorkspaceStorage not found
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Update a WorkspaceStorage object
components:
  parameters:
    id:
      description: The id of record
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: string
      style: simple
  schemas:
    User:
      example:
        organisation_id: organisation_id
        role: role
        name: name
        organisation: organisation
        id: id
        email: email
        username: username
      properties:
        id:
          description: User's ID
          type: string
        name:
          description: User's name
          type: string
        username:
          description: User's username
          type: string
        email:
          description: User's email address
          format: email
          type: string
        organisation:
          description: User's organisation
          type: string
        role:
          description: User's role
          type: string
        organisation_id:
          description: OrganisationID
          type: string
      type: object
    UserCreateRequest:
      example:
        organisation_id: organisation_id
        password: password
        name: name
        organisation: organisation
        email: email
        username: username
      properties:
        name:
          description: User's name
          type: string
        username:
          description: User's username
          type: string
        email:
          description: User's email address
          format: email
          type: string
        password:
          description: Users desired password
          type: string
        organisation:
          description: User's organisation
          type: string
        organisation_id:
          description: OrganisationID
          type: string
      required:
      - email
      - name
      - organisation_id
      - password
      type: object
    LoginRequest:
      example:
        password: password
        email: email
      properties:
        email:
          description: User's email
          type: string
        password:
          description: User's password
          format: password
          type: string
      required:
      - email
      - password
      type: object
    LoginResponse:
      example:
        expires_in: 0
        token: token
      properties:
        token:
          description: Access token for authenticated requests
          type: string
        expires_in:
          description: Token expiration time in seconds
          type: integer
      type: object
    WorkspaceProvisionRequest:
      example:
        ssh_public_key: ssh_public_key
        updated_at: 2000-01-23T04:56:07.000+00:00
        user_id: user_id
        org_id: org_id
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        state: null
        message: message
        status:
          workspace_namespace: workspace_namespace
          cluster_url: cluster_url
          workspace_service_accountname: workspace_service_accountname
          workspace_serviceaccount_token: workspace_serviceaccount_token
          cluster_ca_cert: cluster_ca_cert
          domain: domain
      properties:
        id:
          format: uuid
          type: string
        user_id:
          type: string
        org_id:
          type: string
        ssh_public_key:
          type: string
        status:
          $ref: '#/components/schemas/WorkspaceProvisionRequestStatus'
        state:
          $ref: '#/components/schemas/WorkspaceProvisionRequestState'
        message:
          type: string
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
      required:
      - ssh_public_key
      type: object
    WorkspaceProvisionRequestState:
      enum:
      - Completed
      - Error
      - Pending
      type: string
    WorkspaceProvisionRequestStatus:
      example:
        workspace_namespace: workspace_namespace
        cluster_url: cluster_url
        workspace_service_accountname: workspace_service_accountname
        workspace_serviceaccount_token: workspace_serviceaccount_token
        cluster_ca_cert: cluster_ca_cert
        domain: domain
      properties:
        workspace_namespace:
          nullable: true
          type: string
        workspace_service_accountname:
          nullable: true
          type: string
        workspace_serviceaccount_token:
          nullable: true
          type: string
        cluster_ca_cert:
          nullable: true
          type: string
        cluster_url:
          nullable: true
          type: string
        domain:
          nullable: true
          type: string
      type: object
    Cluster:
      properties:
        id:
          type: string
        name:
          type: string
        organisation_id:
          type: string
        default:
          type: boolean
        cluster_url:
          type: string
        cluster_ca_data:
          type: string
        client_cert_data:
          type: string
        client_key_data:
          type: string
      type: object
    WorkspaceStorage:
      additionalProperties: false
      example:
        organisation_id: organisation_id
        updated_at: 2000-01-23T04:56:07.000+00:00
        name: name
        namespace: namespace
        volumes:
        - name: name
          annotations:
          - value: value
            key: key
          - value: value
            key: key
          id: id
          spec:
            storage_class: storage_class
            size: size
            sync_before_use: true
            source:
              local_source:
                path: path
                sync: true
              build_source:
              - destination_path: destination_path
                resource_ref: resource_ref
                source_path: source_path
              - destination_path: destination_path
                resource_ref: resource_ref
                source_path: source_path
              source_type: null
          labels:
          - value: value
            key: key
          - value: value
            key: key
          status:
            phase: phase
            build_artifact_syncs:
            - build_id: build_id
              resource_name: resource_name
              status: status
            - build_id: build_id
              resource_name: resource_name
              status: status
            conditions:
            - reason: reason
              last_transition_time: 2000-01-23T04:56:07.000+00:00
              type: type
              message: message
              observed_generation: 0
              status: status
            - reason: reason
              last_transition_time: 2000-01-23T04:56:07.000+00:00
              type: type
              message: message
              observed_generation: 0
              status: status
        - name: name
          annotations:
          - value: value
            key: key
          - value: value
            key: key
          id: id
          spec:
            storage_class: storage_class
            size: size
            sync_before_use: true
            source:
              local_source:
                path: path
                sync: true
              build_source:
              - destination_path: destination_path
                resource_ref: resource_ref
                source_path: source_path
              - destination_path: destination_path
                resource_ref: resource_ref
                source_path: source_path
              source_type: null
          labels:
          - value: value
            key: key
          - value: value
            key: key
          status:
            phase: phase
            build_artifact_syncs:
            - build_id: build_id
              resource_name: resource_name
              status: status
            - build_id: build_id
              resource_name: resource_name
              status: status
            conditions:
            - reason: reason
              last_transition_time: 2000-01-23T04:56:07.000+00:00
              type: type
              message: message
              observed_generation: 0
              status: status
            - reason: reason
              last_transition_time: 2000-01-23T04:56:07.000+00:00
              type: type
              message: message
              observed_generation: 0
              status: status
        annotations:
        - value: value
          key: key
        - value: value
          key: key
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        state: null
        ssh_config:
          public_key: public_key
        labels:
        - value: value
          key: key
        - value: value
          key: key
        status:
          phase: phase
          storage_server_service_name: storage_server_service_name
          conditions:
          - reason: reason
            last_transition_time: 2000-01-23T04:56:07.000+00:00
            type: type
            message: message
            observed_generation: 0
            status: status
          - reason: reason
            last_transition_time: 2000-01-23T04:56:07.000+00:00
            type: type
            message: message
            observed_generation: 0
            status: status
      properties:
        id:
          readOnly: true
          type: string
        organisation_id:
          readOnly: true
          type: string
        name:
          type: string
        namespace:
          type: string
        labels:
          items:
            $ref: '#/components/schemas/Label'
          type: array
        annotations:
          items:
            $ref: '#/components/schemas/Annotation'
          type: array
        ssh_config:
          $ref: '#/components/schemas/SSHConfig'
        volumes:
          items:
            $ref: '#/components/schemas/Volume'
          type: array
        status:
          $ref: '#/components/schemas/WorkspaceStorageStatus'
        state:
          $ref: '#/components/schemas/WorkspaceStorageState'
        created_at:
          format: date-time
          readOnly: true
          type: string
        updated_at:
          format: date-time
          readOnly: true
          type: string
      required:
      - name
      - namespace
      - ssh_config
      - volumes
      type: object
    WorkspaceStorageState:
      enum:
      - StoragePending
      - StorageCreating
      - StorageCreated
      - StorageReady
      - StorageFailed
      type: string
    Volume:
      additionalProperties: false
      example:
        name: name
        annotations:
        - value: value
          key: key
        - value: value
          key: key
        id: id
        spec:
          storage_class: storage_class
          size: size
          sync_before_use: true
          source:
            local_source:
              path: path
              sync: true
            build_source:
            - destination_path: destination_path
              resource_ref: resource_ref
              source_path: source_path
            - destination_path: destination_path
              resource_ref: resource_ref
              source_path: source_path
            source_type: null
        labels:
        - value: value
          key: key
        - value: value
          key: key
        status:
          phase: phase
          build_artifact_syncs:
          - build_id: build_id
            resource_name: resource_name
            status: status
          - build_id: build_id
            resource_name: resource_name
            status: status
          conditions:
          - reason: reason
            last_transition_time: 2000-01-23T04:56:07.000+00:00
            type: type
            message: message
            observed_generation: 0
            status: status
          - reason: reason
            last_transition_time: 2000-01-23T04:56:07.000+00:00
            type: type
            message: message
            observed_generation: 0
            status: status
      properties:
        id:
          readOnly: true
          type: string
        name:
          type: string
        labels:
          items:
            $ref: '#/components/schemas/Label'
          type: array
        annotations:
          items:
            $ref: '#/components/schemas/Annotation'
          type: array
        spec:
          $ref: '#/components/schemas/WorkspaceVolumeSpec'
        status:
          $ref: '#/components/schemas/VolumeStatus'
      required:
      - name
      - spec
      type: object
    SSHConfig:
      additionalProperties: false
      example:
        public_key: public_key
      properties:
        public_key:
          description: The SSH public key in OpenSSH format
          type: string
      required:
      - public_key
      type: object
    WorkspaceVolumeSpec:
      additionalProperties: false
      example:
        storage_class: storage_class
        size: size
        sync_before_use: true
        source:
          local_source:
            path: path
            sync: true
          build_source:
          - destination_path: destination_path
            resource_ref: resource_ref
            source_path: source_path
          - destination_path: destination_path
            resource_ref: resource_ref
            source_path: source_path
          source_type: null
      properties:
        size:
          type: string
        storage_class:
          type: string
        sync_before_use:
          type: boolean
        source:
          $ref: '#/components/schemas/VolumeSource'
      required:
      - size
      type: object
    VolumeSource:
      additionalProperties: false
      example:
        local_source:
          path: path
          sync: true
        build_source:
        - destination_path: destination_path
          resource_ref: resource_ref
          source_path: source_path
        - destination_path: destination_path
          resource_ref: resource_ref
          source_path: source_path
        source_type: null
      properties:
        source_type:
          $ref: '#/components/schemas/VolumeSourceTypes'
        local_source:
          $ref: '#/components/schemas/LocalSource'
        build_source:
          items:
            $ref: '#/components/schemas/BuildArtifact'
          type: array
      required:
      - source_type
      type: object
    VolumeSourceTypes:
      enum:
      - Local
      - BuildArtifact
      type: string
    LocalSource:
      example:
        path: path
        sync: true
      properties:
        path:
          type: string
        sync:
          type: boolean
      required:
      - path
      - sync
      type: object
    BuildArtifact:
      example:
        destination_path: destination_path
        resource_ref: resource_ref
        source_path: source_path
      properties:
        resource_ref:
          type: string
        source_path:
          type: string
        destination_path:
          type: string
      required:
      - destination_path
      - resource_ref
      - source_path
      type: object
    WorkspaceStorageStatus:
      example:
        phase: phase
        storage_server_service_name: storage_server_service_name
        conditions:
        - reason: reason
          last_transition_time: 2000-01-23T04:56:07.000+00:00
          type: type
          message: message
          observed_generation: 0
          status: status
        - reason: reason
          last_transition_time: 2000-01-23T04:56:07.000+00:00
          type: type
          message: message
          observed_generation: 0
          status: status
      properties:
        conditions:
          items:
            $ref: '#/components/schemas/Condition'
          type: array
        phase:
          type: string
        storage_server_service_name:
          type: string
      type: object
    VolumeStatus:
      example:
        phase: phase
        build_artifact_syncs:
        - build_id: build_id
          resource_name: resource_name
          status: status
        - build_id: build_id
          resource_name: resource_name
          status: status
        conditions:
        - reason: reason
          last_transition_time: 2000-01-23T04:56:07.000+00:00
          type: type
          message: message
          observed_generation: 0
          status: status
        - reason: reason
          last_transition_time: 2000-01-23T04:56:07.000+00:00
          type: type
          message: message
          observed_generation: 0
          status: status
      properties:
        conditions:
          items:
            $ref: '#/components/schemas/Condition'
          type: array
        phase:
          type: string
        build_artifact_syncs:
          items:
            $ref: '#/components/schemas/BuildArtifactSyncInfo'
          type: array
      type: object
    BuildArtifactSyncInfo:
      example:
        build_id: build_id
        resource_name: resource_name
        status: status
      properties:
        resource_name:
          type: string
        build_id:
          type: string
        status:
          type: string
      type: object
    Condition:
      additionalProperties: false
      example:
        reason: reason
        last_transition_time: 2000-01-23T04:56:07.000+00:00
        type: type
        message: message
        observed_generation: 0
        status: status
      properties:
        type:
          type: string
        status:
          type: string
        observed_generation:
          type: integer
        last_transition_time:
          format: date-time
          type: string
        reason:
          type: string
        message:
          type: string
      type: object
    Label:
      additionalProperties: false
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      required:
      - key
      - value
      type: object
    Annotation:
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      required:
      - key
      - value
      type: object
    Error:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - $ref: '#/components/schemas/Error_allOf'
    ErrorList:
      allOf:
      - $ref: '#/components/schemas/List'
      properties:
        items:
          items:
            $ref: '#/components/schemas/Error'
          type: array
      type: object
    List:
      properties:
        kind:
          type: string
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
      required:
      - items
      - kind
      - page
      - size
      - total
      type: object
    ObjectReference:
      properties:
        id:
          type: string
        kind:
          type: string
        href:
          type: string
      type: object
    _api_v1_organizations__id__workspace_storages_get_200_response:
      example:
        total: 6
        items:
        - organisation_id: organisation_id
          updated_at: 2000-01-23T04:56:07.000+00:00
          name: name
          namespace: namespace
          volumes:
          - name: name
            annotations:
            - value: value
              key: key
            - value: value
              key: key
            id: id
            spec:
              storage_class: storage_class
              size: size
              sync_before_use: true
              source:
                local_source:
                  path: path
                  sync: true
                build_source:
                - destination_path: destination_path
                  resource_ref: resource_ref
                  source_path: source_path
                - destination_path: destination_path
                  resource_ref: resource_ref
                  source_path: source_path
                source_type: null
            labels:
            - value: value
              key: key
            - value: value
              key: key
            status:
              phase: phase
              build_artifact_syncs:
              - build_id: build_id
                resource_name: resource_name
                status: status
              - build_id: build_id
                resource_name: resource_name
                status: status
              conditions:
              - reason: reason
                last_transition_time: 2000-01-23T04:56:07.000+00:00
                type: type
                message: message
                observed_generation: 0
                status: status
              - reason: reason
                last_transition_time: 2000-01-23T04:56:07.000+00:00
                type: type
                message: message
                observed_generation: 0
                status: status
          - name: name
            annotations:
            - value: value
              key: key
            - value: value
              key: key
            id: id
            spec:
              storage_class: storage_class
              size: size
              sync_before_use: true
              source:
                local_source:
                  path: path
                  sync: true
                build_source:
                - destination_path: destination_path
                  resource_ref: resource_ref
                  source_path: source_path
                - destination_path: destination_path
                  resource_ref: resource_ref
                  source_path: source_path
                source_type: null
            labels:
            - value: value
              key: key
            - value: value
              key: key
            status:
              phase: phase
              build_artifact_syncs:
              - build_id: build_id
                resource_name: resource_name
                status: status
              - build_id: build_id
                resource_name: resource_name
                status: status
              conditions:
              - reason: reason
                last_transition_time: 2000-01-23T04:56:07.000+00:00
                type: type
                message: message
                observed_generation: 0
                status: status
              - reason: reason
                last_transition_time: 2000-01-23T04:56:07.000+00:00
                type: type
                message: message
                observed_generation: 0
                status: status
          annotations:
          - value: value
            key: key
          - value: value
            key: key
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          state: null
          ssh_config:
            public_key: public_key
          labels:
          - value: value
            key: key
          - value: value
            key: key
          status:
            phase: phase
            storage_server_service_name: storage_server_service_name
            conditions:
            - reason: reason
              last_transition_time: 2000-01-23T04:56:07.000+00:00
              type: type
              message: message
              observed_generation: 0
              status: status
            - reason: reason
              last_transition_time: 2000-01-23T04:56:07.000+00:00
              type: type
              message: message
              observed_generation: 0
              status: status
        - organisation_id: organisation_id
          updated_at: 2000-01-23T04:56:07.000+00:00
          name: name
          namespace: namespace
          volumes:
          - name: name
            annotations:
            - value: value
              key: key
            - value: value
              key: key
            id: id
            spec:
              storage_class: storage_class
              size: size
              sync_before_use: true
              source:
                local_source:
                  path: path
                  sync: true
                build_source:
                - destination_path: destination_path
                  resource_ref: resource_ref
                  source_path: source_path
                - destination_path: destination_path
                  resource_ref: resource_ref
                  source_path: source_path
                source_type: null
            labels:
            - value: value
              key: key
            - value: value
              key: key
            status:
              phase: phase
              build_artifact_syncs:
              - build_id: build_id
                resource_name: resource_name
                status: status
              - build_id: build_id
                resource_name: resource_name
                status: status
              conditions:
              - reason: reason
                last_transition_time: 2000-01-23T04:56:07.000+00:00
                type: type
                message: message
                observed_generation: 0
                status: status
              - reason: reason
                last_transition_time: 2000-01-23T04:56:07.000+00:00
                type: type
                message: message
                observed_generation: 0
                status: status
          - name: name
            annotations:
            - value: value
              key: key
            - value: value
              key: key
            id: id
            spec:
              storage_class: storage_class
              size: size
              sync_before_use: true
              source:
                local_source:
                  path: path
                  sync: true
                build_source:
                - destination_path: destination_path
                  resource_ref: resource_ref
                  source_path: source_path
                - destination_path: destination_path
                  resource_ref: resource_ref
                  source_path: source_path
                source_type: null
            labels:
            - value: value
              key: key
            - value: value
              key: key
            status:
              phase: phase
              build_artifact_syncs:
              - build_id: build_id
                resource_name: resource_name
                status: status
              - build_id: build_id
                resource_name: resource_name
                status: status
              conditions:
              - reason: reason
                last_transition_time: 2000-01-23T04:56:07.000+00:00
                type: type
                message: message
                observed_generation: 0
                status: status
              - reason: reason
                last_transition_time: 2000-01-23T04:56:07.000+00:00
                type: type
                message: message
                observed_generation: 0
                status: status
          annotations:
          - value: value
            key: key
          - value: value
            key: key
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          state: null
          ssh_config:
            public_key: public_key
          labels:
          - value: value
            key: key
          - value: value
            key: key
          status:
            phase: phase
            storage_server_service_name: storage_server_service_name
            conditions:
            - reason: reason
              last_transition_time: 2000-01-23T04:56:07.000+00:00
              type: type
              message: message
              observed_generation: 0
              status: status
            - reason: reason
              last_transition_time: 2000-01-23T04:56:07.000+00:00
              type: type
              message: message
              observed_generation: 0
              status: status
      properties:
        items:
          items:
            $ref: '#/components/schemas/WorkspaceStorage'
          type: array
        total:
          type: integer
      type: object
    Error_allOf:
      properties:
        code:
          type: string
        reason:
          type: string
        operation_id:
          type: string
      type: object
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      scheme: bearer
      type: http
